<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="santosh" name="com.testng.Iretry_Analyser" tests="7" failures="1" timestamp="2021-12-28T19:48:58 IST" time="0.046" errors="0">
  <testcase name="credentails" time="0.016" classname="com.testng.Iretry_Analyser"/>
  <system-out/>
  <testcase name="credentails1" time="0.000" classname="com.testng.Iretry_Analyser">
    <skipped/>
  </testcase> <!-- credentails1 -->
  <system-out/>
  <testcase name="credentails1" time="0.015" classname="com.testng.Iretry_Analyser">
    <skipped/>
  </testcase> <!-- credentails1 -->
  <system-out/>
  <testcase name="credentails1" time="0.000" classname="com.testng.Iretry_Analyser">
    <skipped/>
  </testcase> <!-- credentails1 -->
  <system-out/>
  <testcase name="credentails1" time="0.015" classname="com.testng.Iretry_Analyser">
    <failure type="java.lang.AssertionError" message="expected [Dhoni] but found [dhoni123 ]">
      <![CDATA[java.lang.AssertionError: expected [Dhoni] but found [dhoni123 ]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.testng.Iretry_Analyser.credentails1(Iretry_Analyser.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- credentails1 -->
  <system-out/>
  <testcase name="credentails1" time="0.000" classname="com.testng.Iretry_Analyser">
    <skipped/>
  </testcase> <!-- credentails1 -->
  <system-out/>
  <testcase name="credentails1" time="0.000" classname="com.testng.Iretry_Analyser">
    <skipped/>
  </testcase> <!-- credentails1 -->
  <system-out/>
</testsuite> <!-- com.testng.Iretry_Analyser -->
